#!/bin/bash
. somelibshit.sh
#db settings
dbuname=root
dbpword=yourPasswordHereOfCourse
invalid=0
#give dat bitch prompts, bitches love prompts
read -p "Enter your username: " username
if id -u $username >/dev/null 2>&1; then
    echo "user already exists."
else
    read -p "Enter [1] for domain or [2] for subdomain: " domaintype
    if [ $domaintype -eq 1 ] 
    then
       read -p "Enter your domain: " domainname
       servername=$domainname" www."$domainname
    elif [ $domaintype -eq 2 ] 
    then
       read -p "Enter your subdomain: " domainname
       servername=$domainname
    else 
       invalid=1
       echo "invalid parameter provided."
    fi
    if [ $invalid -eq 0 ]
    then
        if ls -l /srv/www/$domainname >/devnull 2>&1; then
            echo "domain already exists."
        else
            #everything is satisfied
            read -p "Enter your public key: " publickey
            account_provision
            webspace_provision
            database_provision
            vhost_provision
            user_logs
            #gohome
            cd ~
        fi
    fi
fi
